db:
  name: user

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.schema}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver